import type { NextPage } from "next";
import Head from "next/head";
import Banner from "../components/Banner";
import Header from "../components/Header";
import { GetStaticProps } from "next";
import SmallCard from "../components/SmallCard";
import MediumCard from "../components/MediumCard";
import LargeCard from "../components/LargeCard";
import Footer from "../components/Footer";

interface HomeProps {
  exploreData: {
    key: string;
    img: string;
    location: string;
    distance: string;
  }[];
  cardData: {
    img: string;
    title: string;
  }[];
}

const Home: NextPage<HomeProps> = (props) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header placeholder={null} />
      <Banner />

      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        <section className="pt-6">
          <h2 className="text-4xl font-semibold pb-5">Explore Nearby</h2>

          {/* {Pull the data from a server - API call} */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {props.exploreData.map((item) => (
              <SmallCard
                key={item.img}
                img={item.img}
                location={item.location}
                distance={item.distance}
              />
            ))}
          </div>
        </section>

        <section>
          <h2 className="text-4xl font-semibold py-8">Live Anywhere</h2>
          <div className="flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3 ">
            {props.cardData.map((item) => (
              <MediumCard key={item.title} img={item.img} title={item.title} />
            ))}
          </div>
        </section>

        <LargeCard
          img="https://links.papareact.com/4cj"
          title="The Greatest Outdoors"
          description="Wishlists curated by Airbnb"
          buttonText="Get Inspired"
        />
      </main>

      <footer>
        <Footer />
      </footer>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async (context) => {
  const exploreData = await fetch("https://links.papareact.com/pyp");
  const data = await exploreData.json();
  const cardData = await fetch("https://links.papareact.com/zp1");
  const card = await cardData.json();

  return {
    props: {
      exploreData: data,
      cardData: card,
    },
  };
};

export default Home;
